version: "3"

services:
  amboss-web:
    environment:
      # NGINX settings
      VIRTUAL_NETWORK: nginx-proxy
      VIRTUAL_PORT: 3010
      VIRTUAL_HOST: ${AMBOSS_HOST}
      VIRTUAL_HOST_NAME: "amboss"
      SSL_POLICY: Mozilla-Modern

      # Let's encrypt settings
      LETSENCRYPT_HOST: ${AMBOSS_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-<no value>}
