version: "3"

services:
  amboss-server:
    container_name: amboss-server
    image: "amboss/amboss-server:latest"
    restart: unless-stopped
    environment:
      POSTGRES_URL: "postgres"
      AMBOSS_HOST: ${AMBOSS_PROTOCOL:-https}://${AMBOSS_HOST}
      REDIS_HOST: "redis"
      POSTGRES_HOST: "postgres"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "4000:4000"
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  amboss-event:
    container_name: amboss-event
    image: "amboss/amboss-event:latest"
    restart: unless-stopped
    environment:
      REDIS_HOST: "redis"
      POSTGRES_HOST: "postgres"
    depends_on:
      - amboss-server

  amboss-web:
    container_name: amboss-web
    image: "amboss/amboss-web:latest"
    restart: unless-stopped
    environment:
      SERVER_SSR_URL: "http://amboss-server:4000/graphql"
      SERVER_PATH: "/graphql"
    ports:
      - "3000:3000"
    depends_on:
      - amboss-server

required:
  - "postgres"
  - "redis"
  - "amboss"
recommended:
  - "opt-add-tor"
