version: "3"

services:
  amboss-nest:
    container_name: amboss-nest
    image: "amboss/amboss-nest:edge"
    restart: unless-stopped
    environment:
      AMBOSS_HOST: ${AMBOSS_PROTOCOL:-https}://${AMBOSS_HOST}
      REDIS_HOST: "redis"
      POSTGRES_HOST: "postgres"
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - postgres

  amboss-web:
    container_name: amboss-web
    image: "amboss/amboss-web:edge"
    restart: unless-stopped
    environment:
      SERVER_SSR_URL: "http://amboss-nest:4000/graphql"
      SERVER_PATH: "/graphql"
    ports:
      - "3010:3010"
    depends_on:
      - amboss-nest

required:
  - "postgres"
  - "redis"
  - "amboss"
recommended:
  - "opt-add-tor"
