version: "3"

services:
  bitcoind:
    restart: unless-stopped
    container_name: amboss_bitcoind
    image: btcpayserver/bitcoin:0.21.0
    environment:
      BITCOIN_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BITCOIN_WALLETDIR: "/walletdata"
      BITCOIN_EXTRA_ARGS: |
        rpcport=43782
        rpcbind=0.0.0.0:43782
        rpcallowip=0.0.0.0/0
        port=39388
        whitelist=0.0.0.0/0
        maxmempool=500
    expose:
      - "43782"
      - "39388"
    volumes:
      - "bitcoin_datadir:/data"
      - "bitcoin_wallet_datadir:/walletdata"
  nbxplorer:
    environment:
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://bitcoind:43782/
      NBXPLORER_BTCNODEENDPOINT: bitcoind:39388
    volumes:
      - "bitcoin_datadir:/root/.bitcoin"
volumes:
  bitcoin_datadir:
  bitcoin_wallet_datadir:

required:
  - "nbxplorer"
