# This will expose Amboss, your lightning nodes as hidden services and accept onion peers for your full node.
# Warning: This options is for working around NAT and firewall problems as well as to help protect your customer's privacy.
# This will not protect your privacy against a targeted attack against your own privacy.
# All outbound traffic is not channeled through the TOR SOCKS proxy
version: "3"

services:
  amboss-nest:
    environment:
      AMBOSS_TORRCFILE: /usr/local/etc/tor/torrc-2
      SOCKS_ENDPOINT: socks://tor:9050
    volumes:
      - "tor_servicesdir:/var/lib/tor/hidden_services"
      - "tor_torrcdir:/usr/local/etc/tor/"

  amboss-web:
    environment:
      HIDDENSERVICE_NAME: Amboss
      HIDDENSERVICE_REVERSEPROXY: nginx

  nginx:
    volumes:
      - "tor_servicesdir:/var/lib/tor/hidden_services"
  nginx-gen:
    volumes:
      - "tor_servicesdir:/var/lib/tor/hidden_services"

  tor:
    restart: unless-stopped
    image: btcpayserver/tor:0.4.2.7
    container_name: tor
    environment:
      TOR_PASSWORD: btcpayserver
      TOR_ADDITIONAL_CONFIG: /usr/local/etc/tor/torrc-2
      TOR_EXTRA_ARGS: |
        CookieAuthentication 1
    expose:
      - "9050" # SOCKS
      - "9051" # Tor Control
    volumes:
      - "tor_datadir:/home/tor/.tor"
      - "tor_torrcdir:/usr/local/etc/tor"
      - "tor_servicesdir:/var/lib/tor/hidden_services"

  tor-gen:
    restart: unless-stopped
    image: btcpayserver/docker-gen:0.7.8
    container_name: tor-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./torrc.tmpl:/etc/docker-gen/templates/torrc.tmpl:ro"
      - "tor_torrcdir:/usr/local/etc/tor"
    entrypoint: /usr/local/bin/docker-gen -notify-sighup tor -watch -wait 5s:30s /etc/docker-gen/templates/torrc.tmpl /usr/local/etc/tor/torrc-2
    links:
      - tor

volumes:
  tor_datadir:
  tor_torrcdir:
  tor_servicesdir:
